- name: Load package variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/packages.yaml"

- name: Get installed packages
  ansible.builtin.package_facts:
    manager: apt

- name: Install Linux Packages
  ansible.builtin.package:
    name: "{{ missing_pkgs }}"
    state: present
  vars:
    all_pkgs: "{{ packages + packages_linux }}"
    pkg_names: >-
      {{ all_pkgs | selectattr('linux_name', 'defined') | map(attribute='linux_name') | list
       + all_pkgs | rejectattr('linux_name', 'defined') | map(attribute='name') | list }}
    missing_pkgs: "{{ pkg_names | difference(ansible_facts.packages.keys() | list) }}"
  when: missing_pkgs | length > 0
  become: true

- name: Get current default shell
  ansible.builtin.command:
    cmd: getent passwd {{ ansible_facts['env']['USER'] }}
  register: passwd_entry
  changed_when: false

- name: Set zsh as default shell
  ansible.builtin.command:
    cmd: usermod --shell /bin/zsh {{ ansible_facts['env']['USER'] }}
  become: true
  when: "'/bin/zsh' not in passwd_entry.stdout"
