- name: Check if running in WSL
  ansible.builtin.command: grep -qi microsoft /proc/version
  register: wsl_check
  failed_when: false
  changed_when: false

- name: symlink scripts from ./bin to $HOME/bin
  ansible.builtin.file:
    src: "{{ script }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/bin/{{ script | basename }}"
    state: link
  loop: "{{ lookup('fileglob', playbook_dir + '/../bin/*.sh', wantlist=True) }}"
  loop_control:
    loop_var: script

- name: symlink WSL-only scripts from ./bin/wsl to $HOME/bin
  ansible.builtin.file:
    src: "{{ script }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/bin/{{ script | basename }}"
    state: link
  loop: "{{ lookup('fileglob', playbook_dir + '/../bin/wsl/*', wantlist=True) }}"
  loop_control:
    loop_var: script
  when: wsl_check.rc == 0
