packages:
  - name: curl
  - { name: git, windows_name: mingit } # don't install the bash for windows crap
  - name: grep
  - name: jq
  - name: unzip
  - name: wget
  - { name: gpg, linux_name: gnupg }

packages_linux:
  - name: atool
  - name: zsh

packages_windows:
  # missing:
  # vscode
  # todo: check how settings are saved.
  # notedpad++ had linked settings inside the folder, and missing context registry (C:\Users\nonamethanks\scoop\apps\notepadplusplus\current\install-context.reg)
  # there must be a way to configure persistent data
  # notepad++ is not persising the settings between restarts, maddening
  # C:\Users\nonamethanks\scoop\persist

  # programming
  - name: mise # fix this: needs to use mise to install the rest
  - name: bitwarden-cli
  - name: filezilla
  # utilities
  - name: 7zip
  - name: unigetui
  - name: yt-dlp
  - name: notepadplusplus
